packages:
  - packages/*

catalog:
  '@babel/core': 7.29.0
  '@babel/plugin-transform-runtime': 7.29.0
  '@babel/preset-env': 7.29.0
  '@babel/preset-react': 7.28.5
  '@babel/preset-typescript': 7.28.5
  '@biomejs/biome': 2.3.14
  '@changesets/changelog-github': 0.5.2
  '@changesets/cli': 2.29.8
  '@commitlint/cli': 20.4.1
  '@commitlint/config-conventional': 20.4.1
  '@formatjs/ecma402-abstract': 3.1.1
  '@formatjs/fast-memoize': 3.1.0
  '@formatjs/icu-messageformat-parser': 3.5.1
  '@growthbook/growthbook-react': 1.6.4
  '@manypkg/cli': 0.25.1
  '@rudderstack/analytics-js': 3.28.1
  '@scaleway/use-segment': 1.1.11
  '@segment/analytics-next': 1.81.1
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/react': 16.3.2
  '@types/jest': 30.0.0
  '@types/js-yaml': 4.0.9
  '@types/node': 25.2.1
  '@types/react': 19.2.11
  '@types/react-dom': 19.2.3
  '@typescript/native-preview': 7.0.0-dev.20260208.1
  '@vitejs/plugin-react': 5.1.3
  '@vitest/coverage-istanbul': 4.0.18
  browserslist: 4.28.1
  builtin-modules: 5.0.0
  cookie: 1.1.1
  cross-env: 10.1.0
  date-fns: 4.1.0
  esbuild-plugin-browserslist: 2.0.0
  execa: 9.6.1
  fast-glob: 3.3.3
  filesize: 11.0.13
  globals: 17.3.0
  globby: 16.1.0
  happy-dom: 20.4.0
  history: 5.3.0
  husky: 9.1.7
  international-types: 0.8.1
  intl-messageformat: 11.1.2
  js-yaml: 4.1.1
  jsdom: 27.4.0
  lint-staged: 16.2.7
  mockdate: 3.0.5
  module-from-string: 3.3.1
  oxlint: 1.42.0
  oxlint-tsgolint: 0.11.5
  query-string: 9.3.1
  react: 19.2.4
  react-dom: 19.2.4
  react-router-dom: 6.30.2
  read-pkg: 10.0.0
  shx: 0.4.0
  simple-git: 3.30.0
  tstyche: 6.2.0
  turbo: 2.8.3
  typescript: 5.9.3
  use-deep-compare-effect: 1.8.1
  vite: 7.3.1
  vitest: 4.0.18
  vitest-localstorage-mock: 0.1.2
  wait-for-expect: 4.0.0
  yaml: 2.8.2

catalogMode: strict

packageManagerStrictVersion: true

savePrefix: ''

supportedArchitectures:
  cpu: [x64, arm64]
  os: [darwin, current]
