packages:
  - packages/*

catalog:
  '@babel/core': 7.28.3
  '@babel/eslint-parser': 7.28.0
  '@babel/plugin-transform-runtime': 7.28.3
  '@babel/preset-env': 7.28.3
  '@babel/preset-react': 7.27.1
  '@babel/preset-typescript': 7.27.1
  '@biomejs/biome': 2.2.2
  '@changesets/changelog-github': 0.5.1
  '@changesets/cli': 2.29.6
  '@commitlint/cli': 19.8.1
  '@commitlint/config-conventional': 19.8.1
  '@emotion/eslint-plugin': 11.12.0
  '@eslint/compat': 1.3.2
  '@eslint/eslintrc': 3.3.1
  '@formatjs/ecma402-abstract': 2.3.4
  '@formatjs/fast-memoize': 2.2.7
  '@formatjs/icu-messageformat-parser': 2.11.2
  '@growthbook/growthbook-react': 1.6.1
  '@rudderstack/analytics-js': 3.23.0
  '@scaleway/use-segment': 1.1.11
  '@segment/analytics-next': 1.81.1
  '@stylistic/eslint-plugin': 4.4.1
  '@testing-library/jest-dom': 6.8.0
  '@testing-library/react': 16.3.0
  '@types/jest': 30.0.0
  '@types/node': 22.18.1
  '@types/react': 19.1.12
  '@types/react-dom': 19.1.9
  '@typescript-eslint/eslint-plugin': 8.38.0
  '@typescript-eslint/parser': 8.38.0
  '@vitejs/plugin-react': 4.7.0
  '@vitest/coverage-istanbul': 3.2.4
  browserslist: 4.25.4
  builtin-modules: 5.0.0
  cookie: 1.0.2
  cross-env: 7.0.3
  date-fns: 4.1.0
  esbuild-plugin-browserslist: 1.0.1
  eslint: 9.29.0
  eslint-config-airbnb: 19.0.4
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-eslint-comments: 3.2.0
  eslint-plugin-import: 2.32.0
  eslint-plugin-jsx-a11y: 6.10.2
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 5.2.0
  filesize: 11.0.2
  globals: 16.3.0
  globby: 14.1.0
  happy-dom: 18.0.1
  history: 5.3.0
  husky: 9.1.7
  international-types: 0.8.1
  intl-messageformat: 10.7.16
  lint-staged: 16.1.5
  mockdate: 3.0.5
  module-from-string: 3.3.1
  query-string: 9.2.2
  react: 19.1.1
  react-dom: 19.1.1
  react-router-dom: 6.29.0
  read-pkg: 9.0.1
  shx: 0.4.0
  simple-git: 3.28.0
  tstyche: 4.0.2
  typescript: 5.9.2
  use-deep-compare-effect: 1.8.1
  vite: 7.0.6
  vitest: 3.2.4
  vitest-localstorage-mock: 0.1.2
  wait-for-expect: 3.0.2

catalogMode: strict
