packages:
  - packages/*
catalog:
  "@babel/core": 7.26.10
  "@babel/eslint-parser": 7.27.0
  "@babel/plugin-transform-runtime": 7.26.10
  "@babel/preset-env": 7.26.9
  "@babel/preset-react": 7.26.3
  "@babel/preset-typescript": 7.27.0
  "@biomejs/biome": 1.9.4
  "@changesets/changelog-github": 0.5.1
  "@changesets/cli": 2.29.2
  "@commitlint/cli": 19.8.0
  "@commitlint/config-conventional": 19.8.0
  "@emotion/eslint-plugin": 11.12.0
  "@eslint/compat": 1.2.8
  "@eslint/eslintrc": 3.3.1
  "@formatjs/ecma402-abstract": 2.3.4
  "@formatjs/fast-memoize": 2.2.7
  "@formatjs/icu-messageformat-parser": 2.11.2
  "@growthbook/growthbook-react": 1.4.1
  "@segment/analytics-next": 1.80.0
  "@stylistic/eslint-plugin": 4.2.0
  "@testing-library/jest-dom": 6.6.3
  "@testing-library/react": 16.3.0
  "@types/jest": 29.5.14
  "@types/node": 22.14.1
  "@types/react": 19.1.2
  "@types/react-dom": 19.1.2
  "@typescript-eslint/eslint-plugin": 8.30.1
  "@typescript-eslint/parser": 8.30.1
  "@vitejs/plugin-react": 4.4.1
  "@vitest/coverage-istanbul": 3.1.1
  browserslist: 4.24.4
  builtin-modules: 5.0.0
  cookie: 1.0.2
  cross-env: 7.0.3
  date-fns: 4.1.0
  esbuild-plugin-browserslist: 1.0.0
  eslint: 9.22.0
  eslint-config-airbnb: 19.0.4
  eslint-config-prettier: 10.1.2
  eslint-import-resolver-typescript: 3.10.1
  eslint-plugin-eslint-comments: 3.2.0
  eslint-plugin-import: 2.31.0
  eslint-plugin-jsx-a11y: 6.10.2
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 5.2.0
  filesize: 10.1.6
  globals: 16.0.0
  globby: 14.1.0
  happy-dom: 17.4.4
  history: 5.3.0
  husky: 9.1.7
  international-types: 0.8.1
  intl-messageformat: 10.7.16
  lint-staged: 15.5.1
  mockdate: 3.0.5
  module-from-string: 3.3.1
  query-string: 9.1.1
  react: 19.1.0
  react-dom: 19.1.0
  react-router-dom: 6.29.0
  read-pkg: 9.0.1
  shx: 0.4.0
  simple-git: 3.27.0
  tstyche: 3.5.0
  typescript: 5.8.3
  use-deep-compare-effect: 1.8.1
  vite: 6.3.2
  vitest: 3.1.1
  vitest-localstorage-mock: 0.1.2
  wait-for-expect: 3.0.2
