packages:
  - packages/*

catalog:
  '@babel/core': 7.28.6
  '@babel/eslint-parser': 7.28.6
  '@babel/plugin-transform-runtime': 7.28.5
  '@babel/preset-env': 7.28.6
  '@babel/preset-react': 7.28.5
  '@babel/preset-typescript': 7.28.5
  '@biomejs/biome': 2.3.11
  '@changesets/changelog-github': 0.5.2
  '@changesets/cli': 2.29.8
  '@commitlint/cli': 20.3.1
  '@commitlint/config-conventional': 20.3.1
  '@emotion/eslint-plugin': 11.12.0
  '@eslint/compat': 2.0.1
  '@eslint/eslintrc': 3.3.3
  '@formatjs/ecma402-abstract': 3.1.0
  '@formatjs/fast-memoize': 3.1.0
  '@formatjs/icu-messageformat-parser': 3.5.0
  '@growthbook/growthbook-react': 1.6.2
  '@manypkg/cli': 0.25.1
  '@rudderstack/analytics-js': 3.28.1
  '@scaleway/use-segment': 1.1.11
  '@segment/analytics-next': 1.81.1
  '@stylistic/eslint-plugin': 5.7.0
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/react': 16.3.2
  '@types/jest': 30.0.0
  '@types/js-yaml': 4.0.9
  '@types/node': 25.0.10
  '@types/react': 19.2.9
  '@types/react-dom': 19.2.3
  '@typescript-eslint/eslint-plugin': 8.53.1
  '@typescript-eslint/parser': 8.53.1
  '@typescript/native-preview': 7.0.0-dev.20260122.4
  '@vitejs/plugin-react': 5.1.2
  '@vitest/coverage-istanbul': 4.0.18
  browserslist: 4.28.1
  builtin-modules: 5.0.0
  cookie: 1.1.1
  cross-env: 10.1.0
  date-fns: 4.1.0
  esbuild-plugin-browserslist: 2.0.0
  eslint: 9.39.2
  eslint-config-airbnb: 19.0.4
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-eslint-comments: 3.2.0
  eslint-plugin-import: 2.32.0
  eslint-plugin-jsx-a11y: 6.10.2
  eslint-plugin-oxlint: 1.41.0
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 7.0.1
  execa: 9.6.1
  fast-glob: 3.3.3
  filesize: 11.0.13
  globals: 17.1.0
  globby: 16.1.0
  happy-dom: 20.3.4
  history: 5.3.0
  husky: 9.1.7
  international-types: 0.8.1
  intl-messageformat: 11.1.1
  js-yaml: 4.1.1
  jsdom: 27.4.0
  lint-staged: 16.2.7
  mockdate: 3.0.5
  module-from-string: 3.3.1
  oxlint: 1.41.0
  oxlint-tsgolint: 0.11.1
  query-string: 9.3.1
  react: 19.2.3
  react-dom: 19.2.3
  react-router-dom: 6.30.2
  read-pkg: 10.0.0
  shx: 0.4.0
  simple-git: 3.30.0
  tstyche: 6.0.2
  turbo: 2.7.5
  typescript: 5.9.3
  use-deep-compare-effect: 1.8.1
  vite: 7.3.1
  vitest: 4.0.18
  vitest-localstorage-mock: 0.1.2
  wait-for-expect: 4.0.0
  yaml: 2.8.2

catalogMode: strict

packageManagerStrictVersion: true

savePrefix: ''

supportedArchitectures:
  cpu: [x64, arm64]
  os: [darwin, current]
