import { defineConfig } from 'oxlint'

export default defineConfig({
  plugins: ['oxc'],
  rules: {
    'oxc/approx-constant': 'off',
    'oxc/bad-array-method-on-arguments': 'off',
    'oxc/bad-bitwise-operator': 'off',
    'oxc/bad-char-at-comparison': 'off',
    'oxc/bad-comparison-sequence': 'off',
    'oxc/bad-min-max-func': 'off',
    'oxc/bad-match-all-arg': 'off',
    'oxc/bad-object-literal-comparison': 'off',
    'oxc/bad-replace-all-arg': 'off',
    'oxc/branches-sharing-code': 'off',
    'oxc/const-comparisons': 'off',
    'oxc/double-comparisons': 'off',
    'oxc/erasing-op': 'off',
    'oxc/misrefactored-assign-op': 'off',
    'oxc/missing-throw': 'off',
    'oxc/no-accumulating-spread': 'off',
    'oxc/no-async-await': 'off',
    'oxc/no-async-endpoint-handlers': 'off',
    'oxc/no-barrel-file': 'off',
    'oxc/no-const-enum': 'off',
    'oxc/no-map-spread': 'off',
    'oxc/no-optional-chaining': 'off',
    'oxc/no-rest-spread-properties': 'off',
    'oxc/no-this-in-exported-function': 'off',
    'oxc/number-arg-out-of-range': 'off',
    'oxc/only-used-in-recursion': 'off',
    'oxc/uninvoked-array-callback': 'off',
  },
})
