export type { Blocker, History, Location, To } from 'history'
export type { RouteParams } from 'regexparam'
export { BrowserRouter } from './BrowserRouter'
export { generatePath } from './generatePath'
export { Link } from './Link'
export type { LinkProps } from './Link'
export { matchPath, matchPaths } from './matchPath'
export type { Match, MatchParams, MatchPathOptions, MaybeMatch } from './matchPath'
export { MemoryRouter } from './MemoryRouter'
export { Prompt } from './Prompt'
export { Redirect } from './Redirect'
export type { RedirectProps } from './Redirect'
export { Route } from './Route'
export type { RouteProps, RouteRenderProps } from './Route'
export { Switch } from './Switch'
export { HistoryContext as RouterContext, useHistory } from './useHistory'
export { useLinkProps } from './useLinkProps'
export type { LinkOptions, AnchorProps } from './useLinkProps'
export { useLocation } from './useLocation'
export { useParams } from './useParams'
export { useRouteMatch } from './useRouteMatch'

// Helpers
export { getQueryParamsFromSearchString } from './helpers/getQueryParamsFromSearchString'
export { getSafeQueryParams } from './helpers/getSafeQueryParams'
export { buildQueryString, createRoute, isRoute } from './helpers/route'
export type { RouteObj, RouteObjAny } from './helpers/route'
export { useBlockNavigation, type ShouldBlockCallback } from './helpers/useBlockNavigation'
export { useNavigate } from './helpers/useNavigate'
export { useRouteParams } from './helpers/useRouteParams'
export { useSafeQueryParams } from './helpers/useSafeQueryParams'

// oxlint-disable-next-line typescript/no-deprecated
export { useQueryParams } from './helpers/useQueryParams'
